on: [push, pull_request]
jobs:
  main:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - run: g++ -o liczbaLosowa liczbaLosowa.cpp
      - run: ./liczbaLosowa
